name: JSA ELO Auto Crawler

# 언제 실행할지 정하는 규칙
on:
  schedule:
    # 매 시간 0분에 실행 (한국 시간 기준 매 정시)
    - cron: '0 */6 * * *'
  workflow_dispatch: # 우리가 원할 때 수동으로 버튼 눌러서 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest # 리눅스 컴퓨터를 빌려서 사용함

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # 깃허브에 올린 내 코드를 가져옴

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # 파이썬 3.9 버전을 설치함

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # 필요한 라이브러리 설치

    - name: Run Crawler
      run: python main.py # 우리가 만든 파이썬 파일 실행!
